apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy alongside Home Assistant in the existing namespace (created by
# hawksnest-automation — not recreated here).
namespace: home-automation

resources:
  - deployment.yaml
  - service.yaml
